#!/usr/bin/env python3
"""Validate the standalone Prompt Optimizer release candidate with stdlib only."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import re
import struct
import subprocess
import sys
import zlib
from pathlib import Path
from typing import Any


# The validator rejects generated bytecode so a clean release tree stays portable.
# Disable local bytecode writes before importing the validator's helper module;
# propagate the same boundary to nested evaluation subprocesses.
sys.dont_write_bytecode = True
os.environ["PYTHONDONTWRITEBYTECODE"] = "1"


ROOT = Path(__file__).resolve().parents[1]
PLUGIN = ROOT / "plugins" / "prompt-optimizer"
MODULE_PATH = PLUGIN / "scripts" / "prompt_optimizer.py"
sys.path.insert(0, str(Path(__file__).resolve().parent))

from release_evidence import file_sha256, product_revision  # noqa: E402

REQUIRED_FILES = (
    ".gitignore",
    ".gitattributes",
    "LICENSE",
    "README.md",
    "BRAND.md",
    "CHANGELOG.md",
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "DESIGN.md",
    "design.tokens.json",
    "MAINTAINER-PILOT.md",
    "PROVENANCE.md",
    "PRIVACY.md",
    "PUBLICATION-GATE.md",
    "RELEASE-CHECKLIST.md",
    "SECURITY.md",
    "SUPPORT.md",
    "TERMS.md",
    "THREAT-MODEL.md",
    "pyproject.toml",
    "tests/test_prompt_optimizer.py",
    "tests/test_release_validator.py",
    "tools/demo.py",
    "tools/render_brand_assets.ps1",
    "tools/release_evidence.py",
    "tools/run_evals.py",
    "tools/validate_json_schema.py",
    "tools/validate_release_candidate.py",
    ".agents/plugins/marketplace.json",
    ".claude-plugin/marketplace.json",
    ".github/FUNDING.yml",
    ".github/ISSUE_TEMPLATE/bug_report.yml",
    ".github/ISSUE_TEMPLATE/config.yml",
    ".github/ISSUE_TEMPLATE/feature_request.yml",
    ".github/PULL_REQUEST_TEMPLATE.md",
    ".github/workflows/test.yml",
    "docs/CODEX-INSTALL.md",
    "docs/CLAUDE-INSTALL.md",
    "docs/OPENAI-PLUGIN-SUBMISSION.md",
    "docs/AGENT-SMITH-ROUTER-BRIDGE.md",
    "docs/LAUNCH-MEASUREMENT.md",
    "docs/COMPILER-CONTRACT.md",
    "docs/EVALUATION.md",
    "docs/RECEIPTS.md",
    "docs/RELEASE-EVIDENCE.md",
    "evals/prompt-optimizer-suite.json",
    "evals/run_eval_case.py",
    "plugins/prompt-optimizer/.codex-plugin/plugin.json",
    "plugins/prompt-optimizer/.claude-plugin/plugin.json",
    "plugins/prompt-optimizer/brief.schema.json",
    "plugins/prompt-optimizer/scripts/prompt_optimizer.py",
    "plugins/prompt-optimizer/skills/prompt-optimizer/SKILL.md",
    "plugins/prompt-optimizer/examples/long-request.txt",
    "plugins/prompt-optimizer/examples/optimized-brief.json",
    "submission/openai-plugin-submission.json",
    "plugins/prompt-optimizer/assets/Prompt Optimizer Logo Prompt 120826.md",
    "plugins/prompt-optimizer/assets/Prompt Optimizer Voice-to-Prompt GPT Image 2 Prompt 200826.md",
    "plugins/prompt-optimizer/assets/Prompt Optimizer Voice-to-Prompt GPT Image 2 Master 200826.png",
    "plugins/prompt-optimizer/assets/Logo Generation Manifest 200826.json",
    "plugins/prompt-optimizer/assets/compiled-prompt.txt",
    "plugins/prompt-optimizer/assets/sample-analysis.json",
    "plugins/prompt-optimizer/assets/sample-trace.json",
    "plugins/prompt-optimizer/assets/icon.png",
    "plugins/prompt-optimizer/assets/logo.png",
    "plugins/prompt-optimizer/assets/logo-dark.png",
    "plugins/prompt-optimizer/assets/screenshot1.png",
    "plugins/prompt-optimizer/assets/social-preview.png",
    "validation/Community Review Change Ledger 120826.json",
    "validation/Prompt Optimizer Eval Result 120826.json",
    "validation/Package Verification 120826.json",
    "validation/Codex Plugin Verification 120826.json",
    "validation/Claude Plugin Verification 200826.json",
    "validation/JSON Schema Verification 120826.json",
    "validation/Skill Boundary Transcript 120826.md",
    "validation/Skill Boundary Verification 120826.json",
    "validation/Veteran Maintainer Review 120826.json",
    "validation/Logo Selection and Promotion 200826.json",
)

EVIDENCE_FILES = (
    "validation/Community Review Change Ledger 120826.json",
    "validation/Prompt Optimizer Eval Result 120826.json",
    "validation/Package Verification 120826.json",
    "validation/Codex Plugin Verification 120826.json",
    "validation/Claude Plugin Verification 200826.json",
    "validation/JSON Schema Verification 120826.json",
    "validation/Skill Boundary Transcript 120826.md",
    "validation/Skill Boundary Verification 120826.json",
    "validation/Veteran Maintainer Review 120826.json",
    "validation/Logo Selection and Promotion 200826.json",
)

EXPECTED_PNGS = {
    "plugins/prompt-optimizer/assets/Prompt Optimizer Voice-to-Prompt GPT Image 2 Master 200826.png": (1254, 1254, True),
    "plugins/prompt-optimizer/assets/icon.png": (512, 512, True),
    "plugins/prompt-optimizer/assets/logo.png": (1024, 1024, False),
    "plugins/prompt-optimizer/assets/logo-dark.png": (1024, 1024, False),
    "plugins/prompt-optimizer/assets/screenshot1.png": (1600, 900, False),
    "plugins/prompt-optimizer/assets/social-preview.png": (1600, 900, False),
}

PRIVATE_MARKERS = (
    "agent" + " smith projects",
    "agent" + "-smith-task-force",
    "diggy" + " digital",
    "markeys" + " meta ad specialist",
    "mr" + " krabs",
    "app" + "ollonia",
    "show" + "time",
    "slack" + "-agent-hub",
    "obsidian" + " brains",
    "runtime" + "/astf/",
)

SECRET_PATTERNS = (
    re.compile(r"\bsk-[A-Za-z0-9_-]{16,}"),
    re.compile(r"\bghp_[A-Za-z0-9]{16,}"),
    re.compile(r"\bgithub_pat_[A-Za-z0-9_]{16,}"),
    re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{12,}"),
    re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
)

ABSOLUTE_PATH_PATTERNS = (
    re.compile(r"[A-Za-z]:[\\/]+Users[\\/]+[^\\/\s]+", re.IGNORECASE),
    re.compile(r"/(?:Users|home)/[^/\s]+/"),
)

TEXT_SUFFIXES = {".md", ".json", ".py", ".toml", ".txt", ".yml", ".yaml", ".ps1", ".svg"}
MAX_FILE_BYTES = 1_000_000


def load_json(path: Path) -> Any:
    """Load one UTF-8 JSON artifact from the candidate."""

    return json.loads(path.read_text(encoding="utf-8-sig"))


def sha256(path: Path) -> str:
    """Return a streaming SHA-256 digest for an asset."""

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def current_product_revision() -> str:
    """Return the current non-self-referential product revision digest."""

    revision, _manifest = product_revision(ROOT)
    return revision


def validate_revision_binding(receipt: dict[str, Any], label: str) -> list[str]:
    """Require one generated receipt to name the current product revision."""

    if receipt.get("product_revision_sha256") != current_product_revision():
        return [f"{label} product revision does not match the current candidate"]
    return []


def load_prompt_optimizer() -> Any:
    """Load the shipped optimizer module from the release candidate."""

    spec = importlib.util.spec_from_file_location("candidate_prompt_optimizer", MODULE_PATH)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load optimizer module from {MODULE_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def paeth(left: int, up: int, upper_left: int) -> int:
    """Return the PNG Paeth predictor value for three neighboring bytes."""

    estimate = left + up - upper_left
    distances = (abs(estimate - left), abs(estimate - up), abs(estimate - upper_left))
    return (left, up, upper_left)[distances.index(min(distances))]


def decode_png_rgba(path: Path) -> tuple[int, int, list[bytes]]:
    """Decode a non-interlaced 8-bit RGBA PNG using only the standard library."""

    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    offset = 8
    width = height = bit_depth = color_type = interlace = None
    compressed = bytearray()
    while offset < len(data):
        length = struct.unpack(">I", data[offset : offset + 4])[0]
        kind = data[offset + 4 : offset + 8]
        payload = data[offset + 8 : offset + 8 + length]
        offset += 12 + length
        if kind == b"IHDR":
            width, height, bit_depth, color_type, _, _, interlace = struct.unpack(">IIBBBBB", payload)
        elif kind == b"IDAT":
            compressed.extend(payload)
        elif kind == b"IEND":
            break
    if None in (width, height, bit_depth, color_type, interlace):
        raise ValueError("missing IHDR")
    if bit_depth != 8 or color_type != 6 or interlace != 0:
        raise ValueError(
            f"expected non-interlaced 8-bit RGBA, got depth={bit_depth} type={color_type} interlace={interlace}"
        )
    raw = zlib.decompress(bytes(compressed))
    stride = width * 4
    rows: list[bytes] = []
    previous = bytearray(stride)
    cursor = 0
    for _ in range(height):
        filter_type = raw[cursor]
        cursor += 1
        source = raw[cursor : cursor + stride]
        cursor += stride
        row = bytearray(stride)
        for index, value in enumerate(source):
            left = row[index - 4] if index >= 4 else 0
            up = previous[index]
            upper_left = previous[index - 4] if index >= 4 else 0
            if filter_type == 0:
                decoded = value
            elif filter_type == 1:
                decoded = value + left
            elif filter_type == 2:
                decoded = value + up
            elif filter_type == 3:
                decoded = value + ((left + up) // 2)
            elif filter_type == 4:
                decoded = value + paeth(left, up, upper_left)
            else:
                raise ValueError(f"unsupported PNG filter {filter_type}")
            row[index] = decoded & 0xFF
        rows.append(bytes(row))
        previous = row
    return width, height, rows


def validate_png(path: Path, expected: tuple[int, int, bool]) -> list[str]:
    """Validate PNG dimensions, corner alpha, and transparent-mark coverage."""

    try:
        width, height, rows = decode_png_rgba(path)
    except (OSError, ValueError, zlib.error, struct.error) as exc:
        return [f"{path.relative_to(ROOT)}: PNG decode failed: {exc}"]
    errors: list[str] = []
    expected_width, expected_height, transparent = expected
    if (width, height) != (expected_width, expected_height):
        errors.append(f"{path.relative_to(ROOT)}: expected {expected_width}x{expected_height}, got {width}x{height}")
    corners = (
        rows[0][3],
        rows[0][(width - 1) * 4 + 3],
        rows[height - 1][3],
        rows[height - 1][(width - 1) * 4 + 3],
    )
    expected_alpha = 0 if transparent else 255
    if any(alpha != expected_alpha for alpha in corners):
        state = "transparent" if transparent else "opaque"
        errors.append(f"{path.relative_to(ROOT)}: {state} asset corners have incorrect alpha")
    if transparent:
        opaque_pixels = sum(1 for row in rows for alpha in row[3::4] if alpha >= 240)
        coverage = opaque_pixels / (width * height)
        if not 0.03 <= coverage <= 0.55:
            errors.append(f"{path.relative_to(ROOT)}: subject coverage {coverage:.3f} is outside 0.03-0.55")
    return errors


def validate_required_files() -> list[str]:
    """Return every missing path required by the standalone candidate."""

    return [f"required file is missing: {relative}" for relative in REQUIRED_FILES if not (ROOT / relative).is_file()]


def validate_file_shape() -> list[str]:
    """Reject symlinks, generated bytecode, and oversized candidate files."""

    errors: list[str] = []
    for path in ROOT.rglob("*"):
        relative = path.relative_to(ROOT)
        if ".git" in relative.parts:
            continue
        if path.is_symlink():
            errors.append(f"symlink is not allowed: {relative}")
            continue
        if not path.is_file():
            continue
        if "__pycache__" in relative.parts or path.suffix == ".pyc":
            errors.append(f"generated Python cache is not allowed: {relative}")
        if path.stat().st_size > MAX_FILE_BYTES:
            errors.append(f"file exceeds {MAX_FILE_BYTES} bytes: {relative}")
    return errors


def validate_text_safety() -> list[str]:
    """Scan public text artifacts for secrets, private markers, paths, and placeholders."""

    errors: list[str] = []
    for path in ROOT.rglob("*"):
        relative = path.relative_to(ROOT)
        if ".git" in relative.parts:
            continue
        if not path.is_file() or (path.suffix.lower() not in TEXT_SUFFIXES and path.name != "LICENSE"):
            continue
        try:
            text = path.read_text(encoding="utf-8-sig")
        except UnicodeDecodeError:
            continue
        lower = text.lower()
        for marker in PRIVATE_MARKERS:
            if marker in lower:
                errors.append(f"private marker {marker!r} found in {relative}")
        for pattern in SECRET_PATTERNS:
            if pattern.search(text):
                errors.append(f"secret-like value matched {pattern.pattern!r} in {relative}")
        for pattern in ABSOLUTE_PATH_PATTERNS:
            if pattern.search(text):
                errors.append(f"absolute user path matched {pattern.pattern!r} in {relative}")
        placeholders = ("[" + "todo:", "[" + "todo]")
        if any(marker in lower for marker in placeholders):
            errors.append(f"TODO placeholder found in {relative}")
    return errors


def validate_metadata() -> list[str]:
    """Validate plugin, marketplace, asset-reference, and license metadata."""

    manifest_path = PLUGIN / ".codex-plugin" / "plugin.json"
    marketplace_path = ROOT / ".agents" / "plugins" / "marketplace.json"
    claude_manifest_path = PLUGIN / ".claude-plugin" / "plugin.json"
    claude_marketplace_path = ROOT / ".claude-plugin" / "marketplace.json"
    try:
        manifest = load_json(manifest_path)
        marketplace = load_json(marketplace_path)
        claude_manifest = load_json(claude_manifest_path)
        claude_marketplace = load_json(claude_marketplace_path)
    except (OSError, json.JSONDecodeError) as exc:
        return [f"metadata JSON failed: {exc}"]
    errors: list[str] = []
    if not all(isinstance(value, dict) for value in (manifest, marketplace, claude_manifest, claude_marketplace)):
        return ["OpenAI/Codex and Claude plugin and marketplace metadata must contain JSON objects"]
    expected_manifest = {
        "name": "prompt-optimizer",
        "version": "0.1.0",
        "license": "MIT",
        "homepage": "https://github.com/SpannDaMan/prompt-optimizer",
        "repository": "https://github.com/SpannDaMan/prompt-optimizer",
    }
    for field, expected in expected_manifest.items():
        if manifest.get(field) != expected:
            errors.append(f"plugin.json {field} must be {expected!r}")
    author = manifest.get("author", {})
    if not isinstance(author, dict) or author.get("name") != "SpannDaMan":
        errors.append("plugin.json author.name must be SpannDaMan")
    interface = manifest.get("interface", {})
    if not isinstance(interface, dict):
        errors.append("plugin.json interface must be an object")
        interface = {}
    for field in ("composerIcon", "logo", "logoDark"):
        value = interface.get(field)
        if not isinstance(value, str) or not (PLUGIN / value).is_file():
            errors.append(f"plugin.json interface.{field} must reference an existing asset")
    screenshots = interface.get("screenshots")
    if not isinstance(screenshots, list) or not screenshots:
        errors.append("plugin.json interface.screenshots must contain at least one asset")
    else:
        for value in screenshots:
            if not isinstance(value, str) or not (PLUGIN / value).is_file():
                errors.append(f"plugin.json screenshot is missing: {value!r}")
    expected_public_urls = {
        "privacyPolicyURL": "https://github.com/SpannDaMan/prompt-optimizer/blob/main/PRIVACY.md",
        "termsOfServiceURL": "https://github.com/SpannDaMan/prompt-optimizer/blob/main/TERMS.md",
    }
    for field, expected in expected_public_urls.items():
        if interface.get(field) != expected:
            errors.append(f"plugin.json interface.{field} must be {expected!r}")
    if marketplace.get("name") != "prompt-optimizer":
        errors.append("marketplace name must be prompt-optimizer")
    entries = marketplace.get("plugins")
    if not isinstance(entries, list) or len(entries) != 1:
        errors.append("marketplace must contain exactly one plugin entry")
    else:
        entry = entries[0] if isinstance(entries[0], dict) else {}
        source = entry.get("source", {}) if isinstance(entry.get("source", {}), dict) else {}
        policy = entry.get("policy", {}) if isinstance(entry.get("policy", {}), dict) else {}
        if entry.get("name") != "prompt-optimizer":
            errors.append("marketplace plugin name must be prompt-optimizer")
        if source.get("source") != "local" or source.get("path") != "./plugins/prompt-optimizer":
            errors.append("marketplace source must be local ./plugins/prompt-optimizer")
        if policy != {"installation": "AVAILABLE", "authentication": "ON_INSTALL"}:
            errors.append("marketplace policy must be AVAILABLE with ON_INSTALL authentication")
        if entry.get("category") != "Developer Tools":
            errors.append("marketplace category must be Developer Tools")
    for field, expected in expected_manifest.items():
        if claude_manifest.get(field) != expected:
            errors.append(f"Claude plugin.json {field} must be {expected!r}")
    claude_author = claude_manifest.get("author", {})
    if not isinstance(claude_author, dict) or claude_author.get("name") != "SpannDaMan":
        errors.append("Claude plugin.json author.name must be SpannDaMan")
    if claude_marketplace.get("name") != "prompt-optimizer":
        errors.append("Claude marketplace name must be prompt-optimizer")
    claude_owner = claude_marketplace.get("owner", {})
    if not isinstance(claude_owner, dict) or claude_owner.get("name") != "SpannDaMan":
        errors.append("Claude marketplace owner.name must be SpannDaMan")
    claude_entries = claude_marketplace.get("plugins")
    if not isinstance(claude_entries, list) or len(claude_entries) != 1:
        errors.append("Claude marketplace must contain exactly one plugin entry")
    else:
        claude_entry = claude_entries[0] if isinstance(claude_entries[0], dict) else {}
        if claude_entry.get("name") != "prompt-optimizer":
            errors.append("Claude marketplace plugin name must be prompt-optimizer")
        if claude_entry.get("source") != "./plugins/prompt-optimizer":
            errors.append("Claude marketplace source must be ./plugins/prompt-optimizer")
        if claude_entry.get("version") != "0.1.0":
            errors.append("Claude marketplace version must be 0.1.0")
    try:
        license_text = (ROOT / "LICENSE").read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        errors.append(f"LICENSE read failed: {exc}")
    else:
        if not license_text.startswith("MIT License\n") or "Copyright (c) 2026 SpannDaMan" not in license_text:
            errors.append("LICENSE must be the approved 2026 SpannDaMan MIT license")
    return errors


def validate_cross_platform_packaging() -> list[str]:
    """Validate public policy, funding, submission, and Router-bridge surfaces."""

    errors: list[str] = []
    try:
        funding = (ROOT / ".github" / "FUNDING.yml").read_text(encoding="utf-8")
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        privacy = (ROOT / "PRIVACY.md").read_text(encoding="utf-8")
        terms = (ROOT / "TERMS.md").read_text(encoding="utf-8")
        bridge = (ROOT / "docs" / "AGENT-SMITH-ROUTER-BRIDGE.md").read_text(encoding="utf-8")
        measurement = (ROOT / "docs" / "LAUNCH-MEASUREMENT.md").read_text(encoding="utf-8")
        skill = (PLUGIN / "skills" / "prompt-optimizer" / "SKILL.md").read_text(encoding="utf-8")
        submission = load_json(ROOT / "submission" / "openai-plugin-submission.json")
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        return [f"cross-platform packaging failed: {exc}"]
    if funding.strip() != "github: [SpannDaMan]":
        errors.append("FUNDING.yml must contain only the approved SpannDaMan GitHub Sponsors target")
    for required in ("OpenAI/Codex", "Claude Code", "Agent Smith Router", "FUNDING.yml"):
        if required not in readme:
            errors.append(f"README is missing cross-platform public-readiness marker: {required}")
    if "does not send prompts" not in privacy or "does not include telemetry" not in privacy:
        errors.append("PRIVACY.md must state the no-upload and no-telemetry boundaries")
    if "does not prove semantic equivalence" not in terms:
        errors.append("TERMS.md must retain the semantic-equivalence limitation")
    if "does not guarantee a better route" not in bridge:
        errors.append("Router bridge must reject a guaranteed routing-improvement claim")
    if "Do not use stars alone" not in measurement:
        errors.append("launch measurement must reject stars-only success")
    if "python <plugin-root>/scripts/prompt_optimizer.py" not in skill:
        errors.append("bundled skill must document the package-relative CLI path")
    if not isinstance(submission, dict):
        errors.append("OpenAI submission packet must be a JSON object")
    else:
        if submission.get("submission_type") != "skills_only":
            errors.append("OpenAI submission packet must declare skills_only")
        if len(submission.get("positive_tests", [])) != 5:
            errors.append("OpenAI submission packet must contain five positive tests")
        if len(submission.get("negative_tests", [])) != 3:
            errors.append("OpenAI submission packet must contain three negative tests")
        if submission.get("publication_action") != "none":
            errors.append("OpenAI submission packet must record no publication action")
    return errors


def validate_json_artifacts() -> list[str]:
    """Verify that every committed JSON artifact is readable and syntactically valid."""

    errors: list[str] = []
    for relative in (
        "design.tokens.json",
        ".agents/plugins/marketplace.json",
        ".claude-plugin/marketplace.json",
        "plugins/prompt-optimizer/.codex-plugin/plugin.json",
        "plugins/prompt-optimizer/.claude-plugin/plugin.json",
        "plugins/prompt-optimizer/brief.schema.json",
        "plugins/prompt-optimizer/examples/optimized-brief.json",
        "plugins/prompt-optimizer/assets/sample-analysis.json",
        "plugins/prompt-optimizer/assets/sample-trace.json",
        "plugins/prompt-optimizer/assets/Logo Generation Manifest 200826.json",
        "submission/openai-plugin-submission.json",
        "evals/prompt-optimizer-suite.json",
        "validation/Community Review Change Ledger 120826.json",
        "validation/Prompt Optimizer Eval Result 120826.json",
        "validation/Package Verification 120826.json",
        "validation/Codex Plugin Verification 120826.json",
        "validation/Claude Plugin Verification 200826.json",
        "validation/JSON Schema Verification 120826.json",
        "validation/Skill Boundary Verification 120826.json",
        "validation/Veteran Maintainer Review 120826.json",
        "validation/Logo Selection and Promotion 200826.json",
    ):
        try:
            load_json(ROOT / relative)
        except (OSError, json.JSONDecodeError) as exc:
            errors.append(f"invalid JSON {relative}: {exc}")
    return errors


def validate_logo_provenance() -> list[str]:
    """Require one hash-locked browser GPT Image 2 source and source-only packaging."""

    errors: list[str] = []
    manifest_path = PLUGIN / "assets" / "Logo Generation Manifest 200826.json"
    try:
        manifest = load_json(manifest_path)
    except (OSError, json.JSONDecodeError) as exc:
        return [f"logo generation manifest failed: {exc}"]
    expected_relative = "plugins/prompt-optimizer/assets/Prompt Optimizer Voice-to-Prompt GPT Image 2 Master 200826.png"
    master_path = ROOT / expected_relative
    if manifest.get("canonical_master") != expected_relative:
        errors.append("logo manifest canonical_master mismatch")
    if manifest.get("source_type") != "original_browser_download":
        errors.append("logo manifest source_type must be original_browser_download")
    if "GPT Image 2" not in str(manifest.get("generation_mode", "")):
        errors.append("logo manifest must record GPT Image 2 generation")
    if manifest.get("local_edit_status") != "none":
        errors.append("logo manifest must record no local edits")
    crop = manifest.get("source_crop")
    if not isinstance(crop, dict):
        errors.append("logo manifest must record a deterministic source_crop")
    else:
        try:
            crop_x = int(crop["x"])
            crop_y = int(crop["y"])
            crop_width = int(crop["width"])
            crop_height = int(crop["height"])
            master_width = int(manifest["master_width"])
            master_height = int(manifest["master_height"])
        except (KeyError, TypeError, ValueError):
            errors.append("logo manifest source_crop is incomplete")
        else:
            if crop_width <= 0 or crop_height <= 0 or crop_width != crop_height:
                errors.append("logo manifest source_crop must be a positive square")
            if crop_x < 0 or crop_y < 0 or crop_x + crop_width > master_width or crop_y + crop_height > master_height:
                errors.append("logo manifest source_crop exceeds master bounds")
    if master_path.is_file():
        actual = hashlib.sha256(master_path.read_bytes()).hexdigest()
        if actual != str(manifest.get("master_sha256", "")).casefold():
            errors.append("canonical logo master hash mismatch")
    for retired in (
        "Prompt Optimizer Mini Logo 120826.png",
        "prompt-optimizer-mark.svg",
        "Prompt Optimizer GPT Image 2 Master 140826.png",
        "Prompt Optimizer GPT Image 2 Prompt 140826.md",
        "Logo Generation Manifest 140826.json",
    ):
        if (PLUGIN / "assets" / retired).exists():
            errors.append(f"retired local logo source still exists: {retired}")
    try:
        script = (ROOT / "tools" / "render_brand_assets.ps1").read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        errors.append(f"brand renderer read failed: {exc}")
    else:
        for required in ("Place-Master", "DrawImage", "master_sha256", "original_browser_download", "source_crop"):
            if required not in script:
                errors.append(f"brand renderer is missing source-only control: {required}")
        for forbidden in ("Draw-RouteKitMark", "Draw-OptimizerMark", "function Draw-Mark", "function Mark(", "FillEllipse", "FillPolygon", "DrawLines", "DrawPath", "GraphicsPath"):
            if forbidden.casefold() in script.casefold():
                errors.append(f"brand renderer contains prohibited logo-origin operation: {forbidden}")
    return errors


def validate_logo_selection_evidence() -> list[str]:
    """Bind the operator-selected visual promotion to exact source and derivative bytes."""

    path = ROOT / "validation" / "Logo Selection and Promotion 200826.json"
    try:
        receipt = load_json(path)
    except (OSError, json.JSONDecodeError) as exc:
        return [f"logo selection evidence failed: {exc}"]

    errors: list[str] = []
    if receipt.get("review_type") != "operator_selected_visual_promotion" or receipt.get("status") != "pass":
        errors.append("logo selection receipt must record a passing operator-selected visual promotion")
    errors.extend(validate_revision_binding(receipt, "logo selection receipt"))

    selection = receipt.get("operator_selection")
    if not isinstance(selection, dict) or selection.get("direction") != "Voice-to-Prompt":
        errors.append("logo selection receipt must identify Voice-to-Prompt")
    elif selection.get("status") != "locked" or selection.get("selection_scope") != "private_release_candidate_only":
        errors.append("logo selection receipt must remain locked to the private release candidate")

    source = receipt.get("canonical_source")
    expected_source = "plugins/prompt-optimizer/assets/Prompt Optimizer Voice-to-Prompt GPT Image 2 Master 200826.png"
    if not isinstance(source, dict) or source.get("path") != expected_source:
        errors.append("logo selection receipt canonical source path is invalid")
    else:
        source_path = ROOT / expected_source
        if not source_path.is_file() or source.get("sha256") != file_sha256(source_path):
            errors.append("logo selection receipt canonical source hash is stale")
        if source.get("source_type") != "original_browser_download" or source.get("local_edit_status") != "none":
            errors.append("logo selection receipt must preserve the original browser source")

    provenance = receipt.get("provenance")
    expected_provenance = {
        "prompt_path": "plugins/prompt-optimizer/assets/Prompt Optimizer Voice-to-Prompt GPT Image 2 Prompt 200826.md",
        "manifest_path": "plugins/prompt-optimizer/assets/Logo Generation Manifest 200826.json",
    }
    if not isinstance(provenance, dict):
        errors.append("logo selection receipt provenance is missing")
    else:
        for field, expected_path in expected_provenance.items():
            hash_field = field.replace("_path", "_sha256")
            artifact = ROOT / expected_path
            if provenance.get(field) != expected_path or not artifact.is_file() or provenance.get(hash_field) != file_sha256(artifact):
                errors.append(f"logo selection receipt {field} binding is stale")

    packaging = receipt.get("source_only_packaging")
    derivatives = packaging.get("derivatives") if isinstance(packaging, dict) else None
    if not isinstance(packaging, dict) or any(packaging.get(flag) is not False for flag in ("geometry_changed", "redraw_used", "recolor_used", "inpainting_used")):
        errors.append("logo selection receipt must record source-only packaging")
    if not isinstance(derivatives, dict) or not derivatives:
        errors.append("logo selection receipt derivative hashes are missing")
    else:
        for relative, expected_hash in derivatives.items():
            artifact = ROOT / relative
            if not artifact.is_file() or expected_hash != file_sha256(artifact):
                errors.append(f"logo selection derivative hash is stale: {relative}")

    actual_size = receipt.get("actual_size_qa")
    if not isinstance(actual_size, dict) or actual_size.get("status") != "pass":
        errors.append("logo selection actual-size QA must pass")
    else:
        qa_path = ROOT / str(actual_size.get("path", ""))
        if not qa_path.is_file() or actual_size.get("sha256") != file_sha256(qa_path):
            errors.append("logo selection actual-size QA hash is stale")

    functional_delta = receipt.get("functional_delta")
    if not isinstance(functional_delta, dict) or functional_delta.get("compiler_behavior_changed") is not False:
        errors.append("logo selection receipt must record no compiler behavior change")
    if receipt.get("publication_action") != "none":
        errors.append("logo selection receipt must record no publication action")
    return errors


def validate_sample_analysis() -> list[str]:
    """Compare the committed analysis receipt with a fresh deterministic analysis."""

    try:
        module = load_prompt_optimizer()
        prompt = (PLUGIN / "examples" / "long-request.txt").read_text(encoding="utf-8")
        generated = module.analyze_prompt(prompt)
        saved = load_json(PLUGIN / "assets" / "sample-analysis.json")
    except (OSError, ImportError, json.JSONDecodeError) as exc:
        return [f"sample analysis failed: {exc}"]
    return [] if generated == saved else ["sample-analysis.json does not match a fresh deterministic analysis"]


def validate_sample_trace() -> list[str]:
    """Compare the committed trace receipt with a fresh valid-packet trace."""

    try:
        module = load_prompt_optimizer()
        prompt = (PLUGIN / "examples" / "long-request.txt").read_text(encoding="utf-8")
        brief = load_json(PLUGIN / "examples" / "optimized-brief.json")
        generated = module.trace_brief(prompt, brief)
        saved = load_json(PLUGIN / "assets" / "sample-trace.json")
    except (OSError, ImportError, json.JSONDecodeError, ValueError) as exc:
        return [f"sample trace failed: {exc}"]
    return [] if generated == saved else ["sample-trace.json does not match a fresh valid-packet trace"]


def validate_demo() -> list[str]:
    """Verify demo, committed render, example packet, and README output remain identical."""

    demo = subprocess.run(
        [sys.executable, "-B", str(ROOT / "tools" / "demo.py")],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    errors: list[str] = []
    if demo.returncode != 0:
        return [f"one-command demo failed: {demo.stderr.strip()}"]
    try:
        compiled = (PLUGIN / "assets" / "compiled-prompt.txt").read_text(encoding="utf-8")
        brief = load_json(PLUGIN / "examples" / "optimized-brief.json")
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
    except (OSError, json.JSONDecodeError) as exc:
        return [f"demo evidence read failed: {exc}"]
    if demo.stdout.rstrip("\r\n") != compiled.rstrip("\r\n"):
        errors.append("tools/demo.py output does not match compiled-prompt.txt")
    if demo.stdout.rstrip("\r\n") != str(brief.get("compiled_prompt", {}).get("text", "")):
        errors.append("tools/demo.py output does not match optimized-brief.json")
    if demo.stdout.strip() not in readme:
        errors.append("README.md does not contain the exact one-command demo output")
    return errors


def validate_review_evidence() -> list[str]:
    """Require durable synthetic-community and simulated-maintainer review ledgers."""

    community_path = ROOT / "validation" / "Community Review Change Ledger 120826.json"
    veteran_path = ROOT / "validation" / "Veteran Maintainer Review 120826.json"
    try:
        community = load_json(community_path)
        veteran = load_json(veteran_path)
    except (OSError, json.JSONDecodeError) as exc:
        return [f"review evidence failed: {exc}"]
    errors: list[str] = []
    caveat = "This is a qualitative synthetic pretest only. No conversion, scale, or demand claims permitted."
    if community.get("review_type") != "synthetic_github_community_pretest":
        errors.append("community review_type is invalid")
    if community.get("panel_size") != 6 or community.get("status") != "pass":
        errors.append("community review must record six passing synthetic perspectives")
    if community.get("evidence_boundary") != caveat:
        errors.append("community review must carry the exact synthetic-evidence boundary")
    if not isinstance(community.get("implemented_changes"), list) or not community.get("implemented_changes"):
        errors.append("community review must list implemented changes")
    errors.extend(validate_revision_binding(community, "community review"))
    if veteran.get("review_type") != "final_private_release_review":
        errors.append("veteran maintainer review_type is invalid")
    if veteran.get("reviewer_type") != "simulated_veteran_open_source_maintainer":
        errors.append("veteran maintainer reviewer_type is invalid")
    verdict = veteran.get("verdict")
    status_pairs = {
        "hold": "blocked",
        "private_pilot_ready": "eligible_for_private_pilot",
        "public_release_ready_with_gates": "eligible_for_separate_publication_decision_after_gates",
    }
    if verdict not in status_pairs or veteran.get("status") != status_pairs.get(verdict):
        errors.append("veteran maintainer verdict and status are incompatible")
    revision_identity = veteran.get("revision_identity")
    if not isinstance(revision_identity, dict) or revision_identity.get("revision") != current_product_revision():
        errors.append("veteran maintainer revision identity does not match the current candidate")
    open_findings = veteran.get("open_p0_p1_p2")
    if not isinstance(open_findings, dict) or set(open_findings) != {"P0", "P1", "P2"}:
        errors.append("veteran maintainer open_p0_p1_p2 must contain P0, P1, and P2 arrays")
    elif any(not isinstance(open_findings[level], list) for level in ("P0", "P1", "P2")):
        errors.append("veteran maintainer blocking finding fields must be arrays")
    elif any(open_findings[level] for level in ("P0", "P1", "P2")):
        errors.append("veteran maintainer review must close all P0, P1, and P2 findings")
    findings = veteran.get("finding_ids")
    if not isinstance(findings, list) or any(
        not isinstance(item, dict)
        or not isinstance(item.get("id"), str)
        or item.get("status") not in {"closed", "partially_closed", "open", "superseded"}
        for item in findings
    ):
        errors.append("veteran maintainer finding registry is malformed")
    if verdict == "hold":
        errors.append("veteran maintainer review still holds the private candidate")
    errors.extend(validate_revision_binding(veteran, "veteran maintainer review"))
    if community.get("publication_action") != "none" or veteran.get("publication_action") != "none":
        errors.append("review evidence must record no publication action")
    return errors


def validate_package_evidence() -> list[str]:
    """Require a passing clean-install and installed-command verification receipt."""

    path = ROOT / "validation" / "Package Verification 120826.json"
    try:
        receipt = load_json(path)
    except (OSError, json.JSONDecodeError) as exc:
        return [f"package evidence failed: {exc}"]
    errors: list[str] = []
    if receipt.get("candidate") != "prompt-optimizer 0.1.0" or receipt.get("status") != "pass":
        errors.append("package verification must pass for prompt-optimizer 0.1.0")
    checks = receipt.get("checks")
    if not isinstance(checks, list) or len(checks) < 7 or any(item.get("status") != "pass" for item in checks if isinstance(item, dict)):
        errors.append("package verification must record all clean-install and installed-command checks as passing")
    wheel = receipt.get("wheel")
    if not isinstance(wheel, dict) or not re.fullmatch(r"[a-f0-9]{64}", str(wheel.get("sha256", ""))):
        errors.append("package verification must record a valid wheel SHA-256")
    errors.extend(validate_revision_binding(receipt, "package verification"))
    if receipt.get("publication_action") != "none":
        errors.append("package verification must record no publication action")
    return errors


def validate_eval_evidence() -> list[str]:
    """Require the committed native eval receipt to match a fresh full-suite run."""

    path = ROOT / "validation" / "Prompt Optimizer Eval Result 120826.json"
    try:
        result = load_json(path)
    except (OSError, json.JSONDecodeError) as exc:
        return [f"eval evidence failed: {exc}"]
    errors: list[str] = []
    if result.get("suite_id") != "prompt-optimizer-public-candidate-v0.1.0":
        errors.append("eval suite_id is invalid")
    if result.get("pass") is not True or result.get("score") != 1.0:
        errors.append("native prompt-agent eval must pass at score 1.0")
    if result.get("case_count") != 13 or result.get("critical_failure_cases") != [] or result.get("error_cases") != []:
        errors.append("native prompt-agent eval must pass all thirteen cases without critical or runner failures")
    errors.extend(validate_revision_binding(result, "native prompt-agent eval"))
    fresh = subprocess.run(
        [sys.executable, "-B", str(ROOT / "tools" / "run_evals.py")],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if fresh.returncode != 0:
        errors.append(f"fresh native prompt-agent eval failed: {fresh.stderr.strip()}")
    else:
        try:
            generated = json.loads(fresh.stdout)
        except json.JSONDecodeError as exc:
            errors.append(f"fresh native prompt-agent eval emitted invalid JSON: {exc}")
        else:
            if generated != result:
                errors.append("committed native prompt-agent eval receipt does not match a fresh full-suite run")
    return errors


def validate_plugin_evidence() -> list[str]:
    """Require revision-bound evidence from the official local plugin validator."""

    path = ROOT / "validation" / "Codex Plugin Verification 120826.json"
    try:
        receipt = load_json(path)
    except (OSError, json.JSONDecodeError) as exc:
        return [f"Codex plugin evidence failed: {exc}"]
    errors: list[str] = []
    if receipt.get("status") != "pass" or receipt.get("exit_code") != 0:
        errors.append("Codex plugin verification must pass with exit code 0")
    if receipt.get("validated_plugin_path") != "plugins/prompt-optimizer":
        errors.append("Codex plugin verification path is invalid")
    tool = receipt.get("tool")
    if not isinstance(tool, dict) or not re.fullmatch(r"[a-f0-9]{64}", str(tool.get("sha256", ""))):
        errors.append("Codex plugin verification must identify the validator by SHA-256")
    command = receipt.get("command")
    if not isinstance(command, list) or not command or any(not isinstance(item, str) or not item for item in command):
        errors.append("Codex plugin verification must record the exact command")
    errors.extend(validate_revision_binding(receipt, "Codex plugin verification"))
    if receipt.get("publication_action") != "none":
        errors.append("Codex plugin verification must record no publication action")
    return errors


def validate_claude_plugin_evidence() -> list[str]:
    """Require a passing native Claude plugin and marketplace verification receipt."""

    path = ROOT / "validation" / "Claude Plugin Verification 200826.json"
    try:
        receipt = load_json(path)
    except (OSError, json.JSONDecodeError) as exc:
        return [f"Claude plugin evidence failed: {exc}"]
    errors: list[str] = []
    if receipt.get("status") != "pass":
        errors.append("Claude plugin verification must pass")
    if receipt.get("validated_paths") != [".", "plugins/prompt-optimizer"]:
        errors.append("Claude plugin verification paths are invalid")
    checks = receipt.get("checks")
    if not isinstance(checks, list) or len(checks) != 2:
        errors.append("Claude plugin verification must record marketplace and plugin checks")
    elif any(not isinstance(item, dict) or item.get("exit_code") != 0 for item in checks):
        errors.append("Claude plugin verification checks must exit 0")
    tool = receipt.get("tool")
    if not isinstance(tool, dict) or tool.get("identity") != "sha256" or not tool.get("sha256"):
        errors.append("Claude plugin verification must identify the CLI by SHA-256")
    errors.extend(validate_revision_binding(receipt, "Claude plugin verification"))
    if receipt.get("publication_action") != "none":
        errors.append("Claude plugin verification must record no publication action")
    return errors


def validate_schema_evidence() -> list[str]:
    """Run the independent schema validator and verify its bound receipt."""

    path = ROOT / "validation" / "JSON Schema Verification 120826.json"
    try:
        receipt = load_json(path)
    except (OSError, json.JSONDecodeError) as exc:
        return [f"JSON Schema evidence failed: {exc}"]
    errors: list[str] = []
    completed = subprocess.run(
        [
            sys.executable,
            "-B",
            str(ROOT / "tools" / "validate_json_schema.py"),
            "--schema",
            str(PLUGIN / "brief.schema.json"),
            "--instance",
            str(PLUGIN / "examples" / "optimized-brief.json"),
        ],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    try:
        fresh = json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        errors.append(f"fresh JSON Schema validation emitted invalid JSON: {exc}")
    else:
        if completed.returncode != 0 or fresh != {"status": "pass", "errors": []}:
            errors.append("fresh JSON Schema validation failed")
    if receipt.get("status") != "pass" or receipt.get("exit_code") != 0 or receipt.get("errors") != []:
        errors.append("JSON Schema verification receipt must record a clean pass")
    errors.extend(validate_revision_binding(receipt, "JSON Schema verification"))
    if receipt.get("publication_action") != "none":
        errors.append("JSON Schema verification must record no publication action")
    return errors


def validate_skill_boundary() -> list[str]:
    """Keep the bundled skill compiler-only and verify its controlled transcript."""

    skill_path = PLUGIN / "skills" / "prompt-optimizer" / "SKILL.md"
    receipt_path = ROOT / "validation" / "Skill Boundary Verification 120826.json"
    transcript_path = ROOT / "validation" / "Skill Boundary Transcript 120826.md"
    try:
        skill = skill_path.read_text(encoding="utf-8")
        receipt = load_json(receipt_path)
        transcript = transcript_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        return [f"skill boundary evidence failed: {exc}"]
    errors: list[str] = []
    required = "This skill is a compiler only: do not execute the source task or the compiled prompt."
    if required not in skill:
        errors.append("skill must contain the compiler-only handoff")
    if "keep the json packet as evidence and continue" in skill.lower():
        errors.append("skill must not continue into source-task execution")
    if receipt.get("status") != "pass" or receipt.get("source_task_executed") is not False:
        errors.append("controlled skill boundary verification must end without source-task execution")
    if receipt.get("transcript_path") != "validation/Skill Boundary Transcript 120826.md":
        errors.append("skill boundary verification transcript path is invalid")
    if receipt.get("transcript_sha256") != file_sha256(transcript_path):
        errors.append("skill boundary verification transcript hash is stale")
    if "Source task execution observed: `false`" not in transcript or "Compiled artifact returned: `true`" not in transcript:
        errors.append("controlled skill transcript does not establish compiler-only termination")
    errors.extend(validate_revision_binding(receipt, "skill boundary verification"))
    if receipt.get("publication_action") != "none":
        errors.append("skill boundary verification must record no publication action")
    return errors


def validate_claims() -> list[str]:
    """Reject unqualified preservation or performance claims in discovery copy."""

    paths = (ROOT / "README.md", ROOT / "BRAND.md", PLUGIN / ".codex-plugin" / "plugin.json")
    patterns = (
        re.compile(r"without losing constraints", re.IGNORECASE),
        re.compile(r"guarantee(?:d|s)? (?:constraint|semantic|prompt)", re.IGNORECASE),
        re.compile(r"semantic equivalence is proven", re.IGNORECASE),
        re.compile(r"improves every prompt", re.IGNORECASE),
    )
    errors: list[str] = []
    for path in paths:
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            errors.append(f"claims scan failed for {path.relative_to(ROOT)}: {exc}")
            continue
        for pattern in patterns:
            if pattern.search(text):
                errors.append(f"unqualified claim matched in {path.relative_to(ROOT)}: {pattern.pattern}")
    return errors


def validate_private_pilot_contract() -> list[str]:
    """Require a consistent post-release maintainer-pilot contract."""

    paths = (
        ROOT / "MAINTAINER-PILOT.md",
        ROOT / "README.md",
        ROOT / "PUBLICATION-GATE.md",
        ROOT / "RELEASE-CHECKLIST.md",
    )
    try:
        texts = {path.name: path.read_text(encoding="utf-8") for path in paths}
    except (OSError, UnicodeDecodeError) as exc:
        return [f"private pilot contract read failed: {exc}"]
    combined = "\n".join(texts.values()).lower()
    errors: list[str] = []
    for forbidden in (
        "must finish before any public-release decision",
        "no public repository",
        "private maintainer pilot that precedes",
    ):
        if forbidden in combined:
            errors.append(f"maintainer pilot retains superseded pre-publication gate: {forbidden}")
    pilot = texts["MAINTAINER-PILOT.md"].lower()
    for required in (
        "spanndaman",
        "no more than five",
        "private issue or feedback log",
        "triage twice",
        "change control",
        "stop conditions",
        "support minutes",
        "day-30 decision",
        "post-release",
        "public repository may remain live",
        "explicitly overridden",
    ):
        if required not in pilot:
            errors.append(f"private pilot contract is missing: {required}")
    return errors


def validate_png_assets() -> tuple[list[str], dict[str, str]]:
    """Validate every required PNG once and return its stable digest map."""

    errors: list[str] = []
    asset_hashes: dict[str, str] = {}
    for relative, expected in EXPECTED_PNGS.items():
        path = ROOT / relative
        if not path.is_file():
            errors.append(f"PNG asset is missing: {relative}")
            continue
        errors.extend(validate_png(path, expected))
        try:
            asset_hashes[relative] = sha256(path)
        except OSError as exc:
            errors.append(f"cannot hash PNG asset {relative}: {exc}")
    return errors, asset_hashes


def run_validation() -> dict[str, Any]:
    """Run every release check once and return one internally consistent receipt."""

    png_errors, asset_hashes = validate_png_assets()
    check_errors = {
        "required_files": validate_required_files(),
        "portable_file_shape": validate_file_shape(),
        "text_safety": validate_text_safety(),
        "metadata": validate_metadata(),
        "cross_platform_packaging": validate_cross_platform_packaging(),
        "json_artifacts": validate_json_artifacts(),
        "logo_provenance": validate_logo_provenance(),
        "logo_selection_evidence": validate_logo_selection_evidence(),
        "sample_analysis": validate_sample_analysis(),
        "sample_trace": validate_sample_trace(),
        "one_command_demo": validate_demo(),
        "native_prompt_agent_eval": validate_eval_evidence(),
        "package_evidence": validate_package_evidence(),
        "codex_plugin_evidence": validate_plugin_evidence(),
        "claude_plugin_evidence": validate_claude_plugin_evidence(),
        "json_schema_evidence": validate_schema_evidence(),
        "skill_boundary": validate_skill_boundary(),
        "claims_integrity": validate_claims(),
        "private_pilot_contract": validate_private_pilot_contract(),
        "review_evidence": validate_review_evidence(),
        "png_assets": png_errors,
    }
    errors = sorted({error for group in check_errors.values() for error in group})
    evidence_hashes = {
        relative: file_sha256(ROOT / relative)
        for relative in EVIDENCE_FILES
        if (ROOT / relative).is_file()
    }
    return {
        "status": "pass" if not errors else "fail",
        "candidate": "prompt-optimizer 0.1.0",
        "product_revision_sha256": current_product_revision(),
        "root": ".",
        "checks": {name: "pass" if not group else "fail" for name, group in check_errors.items()},
        "asset_sha256": asset_hashes,
        "evidence_sha256": evidence_hashes,
        "errors": errors,
    }


def main() -> int:
    """Run the release validator CLI and render human or JSON output."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", help="Emit the full JSON validation receipt.")
    args = parser.parse_args()
    result = run_validation()
    if args.json:
        print(json.dumps(result, indent=2))
    elif result["status"] == "pass":
        print("PASS: Prompt Optimizer release candidate")
    else:
        print("FAIL: Prompt Optimizer release candidate", file=sys.stderr)
        for error in result["errors"]:
            print(f"- {error}", file=sys.stderr)
    return 0 if result["status"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
